<?php

namespace Database\Seeders;

use App\Models\Task;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tasks = array(
            array(
                "id" => 1,
                "title" => "tincidunt eget tempus vel pede morbi porttitor lorem",
                "completed" => 0,
                "starred" => 0,
                "important" => 0,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 2,
                "title" => "feugiat non pretium quis lectus suspendisse",
                "completed" => 1,
                "starred" => 1,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 3,
                "title" => "nulla tellus in sagittis dui vel",
                "completed" => 0,
                "starred" => 0,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 4,
                "title" => "gravida nisi at nibh in hac",
                "completed" => 0,
                "starred" => 0,
                "important" => 1,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 5,
                "title" => "ut mauris eget massa tempor convallis nulla neque",
                "completed" => 0,
                "starred" => 1,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 6,
                "title" => "hac habitasse platea dictumst morbi vestibulum velit",
                "completed" => 0,
                "starred" => 1,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 7,
                "title" => "vel enim sit amet nunc viverra",
                "completed" => 1,
                "starred" => 1,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 8,
                "title" => "pede justo lacinia eget tincidunt eget tempus vel",
                "completed" => 1,
                "starred" => 0,
                "important" => 0,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 9,
                "title" => "neque sapien placerat ante nulla justo aliquam",
                "completed" => 0,
                "starred" => 1,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 10,
                "title" => "sit amet sapien dignissim vestibulum vestibulum",
                "completed" => 0,
                "starred" => 0,
                "important" => 1,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 11,
                "title" => "massa volutpat convallis morbi odio odio",
                "completed" => 1,
                "starred" => 1,
                "important" => 0,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 12,
                "title" => "quis augue luctus tincidunt nulla mollis molestie",
                "completed" => 0,
                "starred" => 1,
                "important" => 0,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 13,
                "title" => "faucibus orci luctus et ultrices posuere cubilia curae",
                "completed" => 0,
                "starred" => 1,
                "important" => 0,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 14,
                "title" => "pede venenatis non sodales sed tincidunt eu felis",
                "completed" => 0,
                "starred" => 1,
                "important" => 0,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 15,
                "title" => "volutpat dui maecenas tristique est et",
                "completed" => 0,
                "starred" => 0,
                "important" => 1,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 16,
                "title" => "turpis donec posuere metus vitae ipsum aliquam",
                "completed" => 0,
                "starred" => 0,
                "important" => 1,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 17,
                "title" => "platea dictumst aliquam augue quam sollicitudin vitae",
                "completed" => 0,
                "starred" => 0,
                "important" => 0,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 18,
                "title" => "mauris ullamcorper purus sit amet nulla quisque",
                "completed" => 1,
                "starred" => 1,
                "important" => 1,
                "trashed" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 19,
                "title" => "quis lectus suspendisse potenti in eleifend",
                "completed" => 0,
                "starred" => 1,
                "important" => 0,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 20,
                "title" => "non mattis pulvinar nulla pede ullamcorper augue a",
                "completed" => 1,
                "starred" => 0,
                "important" => 0,
                "trashed" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
        );

        Task::insert($tasks);
    }
}
